using System.Text.RegularExpressions;

namespace Teavel.M365;

/// <summary>재고를 훑을 때 이 그룹이 어느 무더기에 속하는지.</summary>
public enum TriageBucket
{
    /// <summary>실제로 쓰이고 있다 — 사람이 여럿 들어 있다.</summary>
    InUse,

    /// <summary>정리해 볼 만하다 — 시험용 이름이거나 사람이 거의 없다.</summary>
    Candidate,

    /// <summary>
    /// Microsoft 365 가 스스로 만든 것 — 건드리면 안 된다.
    /// 'All Company' 처럼 구성원이 0명으로 보이는 것들이 있어, 조심하지 않으면
    /// 정리 후보로 올라간다.
    /// </summary>
    System,
}

/// <summary>별칭이 쓸 만한지.</summary>
public enum AliasQuality
{
    /// <summary>사람이 읽을 수 있고 뜻이 남아 있다.</summary>
    Fine,

    /// <summary>Teams 가 자동으로 만든 것(msteams_83a1ec 같은 것).</summary>
    AutoGenerated,

    /// <summary>이름에서 뜻이 날아갔다 — 한글 이름으로 만들면 이렇게 된다.</summary>
    Degenerate,
}

/// <summary>재고 한 줄에 대한 판단.</summary>
/// <param name="Group">그 그룹.</param>
/// <param name="Bucket">어느 무더기인지.</param>
/// <param name="Alias">별칭 품질.</param>
/// <param name="Note">교사에게 보여줄 한 줄. 없으면 빈 문자열.</param>
public sealed record TriagedGroup(
    ExistingGroup Group,
    TriageBucket Bucket,
    AliasQuality Alias,
    string Note);

/// <summary>
/// 재고를 훑어보기 좋게 나눈다.
///
/// 실제 학교 테넌트를 열어 보고 만든 것이다. 거기엔 수업 그룹(30명·203명)과
/// 시험용 잔재(Test·TEST·테스트·히히, 1~2명)와 개인 그룹이 섞여 있었다.
/// 관리자가 보고 싶은 것은 "무엇을 지워도 되나" 인데, 그 판단의 재료는
/// <b>이름의 생김새와 사람 수</b> 두 가지다.
///
/// 여기서 지우지 않는다. 무더기로 나눠 보여줄 뿐이고, 지울지 이름을 바꿀지는
/// 관리자가 하나씩 정한다 — 잘못 지우면 파일·대화가 함께 사라지기 때문이다.
/// </summary>
public static class InventoryTriage
{
    // Teams 앱에서 만들면 별칭이 이렇게 붙는다 — 사람이 읽을 수 없다.
    private static readonly Regex AutoAlias = new(@"^msteams_[0-9a-f]+$",
        RegexOptions.Compiled | RegexOptions.IgnoreCase);

    // 시험용으로 만들어 두고 잊은 것들. 이름 전체가 이 꼴일 때만 본다 —
    // '테스트지 채점' 같은 진짜 업무 그룹을 잡으면 안 된다.
    private static readonly Regex TestLike = new(
        @"^(test|테스트|시험|샘플|sample|temp|임시|연습|asdf|ㅁㄴㅇㄹ|하이|히히|ㅋㅋ+|ㅎㅎ+)[\s_-]*\d*$",
        RegexOptions.Compiled | RegexOptions.IgnoreCase);

    /// <summary>사람이 이만큼 이하면 '쓰이지 않는 것 같다' 고 본다.</summary>
    public const int QuietMemberCount = 2;

    /// <summary>재고를 무더기로 나눈다. 쓰이는 것이 앞, 정리 후보가 뒤.</summary>
    public static IReadOnlyList<TriagedGroup> Triage(IReadOnlyList<ExistingGroup> groups)
    {
        var result = new List<TriagedGroup>();

        foreach (var g in groups)
        {
            var alias = JudgeAlias(g);
            var reasons = new List<string>();

            var name = g.DisplayName.Trim();

            // Microsoft 365 가 스스로 만든 것은 무더기부터 다르다.
            // 'All Company' 는 동적 그룹이라 구성원이 0명으로 보이는데,
            // 그대로 두면 '구성원 없음' 이라며 정리 후보로 올라간다 — 지우면 안 되는 것이다.
            if (IsSystemGroup(g))
            {
                result.Add(new TriagedGroup(g, TriageBucket.System, alias,
                    "Microsoft 365 가 만든 그룹입니다. 지우지 마세요."));
                continue;
            }

            var looksTest = TestLike.IsMatch(name);
            var quiet = g.MemberCount is >= 0 and <= QuietMemberCount;

            if (looksTest) reasons.Add("시험용으로 보이는 이름");
            if (quiet) reasons.Add(g.MemberCount == 0 ? "구성원이 없음" : $"구성원 {g.MemberCount}명뿐");

            // 둘 중 하나만으로는 섣부르다. 이름이 시험용처럼 보이거나 사람이 거의 없으면
            // 후보로 올리되, 판단은 관리자에게 남긴다.
            var bucket = (looksTest || quiet) ? TriageBucket.Candidate : TriageBucket.InUse;

            if (alias == AliasQuality.AutoGenerated)
                reasons.Add("Teams 가 자동으로 붙인 별칭");
            else if (alias == AliasQuality.Degenerate)
                reasons.Add($"별칭 '{g.MailNickname}' 에 뜻이 남아 있지 않음");

            result.Add(new TriagedGroup(g, bucket, alias, string.Join(" · ", reasons)));
        }

        // 쓰이는 것 먼저, 그 안에서는 사람 많은 순.
        return result
            .OrderBy(t => t.Bucket)
            .ThenByDescending(t => t.Group.MemberCount)
            .ThenBy(t => t.Group.DisplayName, StringComparer.CurrentCulture)
            .ToList();
    }

    /// <summary>
    /// Microsoft 365 가 스스로 만든 그룹인지.
    /// </summary>
    /// <remarks>
    /// 'All Company' 는 테넌트를 만들면 자동으로 생기는 조직 전체 그룹이다.
    /// 동적 그룹이라 GroupMemberCount 가 0 으로 오는데, 지우면 안 된다.
    /// 별칭이 <c>AllCompany.&lt;숫자&gt;.&lt;임의문자&gt;</c> 꼴인 것으로 알아본다 —
    /// 이름은 테넌트 언어에 따라 달라질 수 있어 별칭이 더 믿을 만하다.
    /// </remarks>
    public static bool IsSystemGroup(ExistingGroup g)
        => Regex.IsMatch(g.MailNickname.Trim(), @"^AllCompany\.", RegexOptions.IgnoreCase)
        || string.Equals(g.DisplayName.Trim(), "All Company", StringComparison.OrdinalIgnoreCase);

    /// <summary>
    /// 별칭이 쓸 만한지 본다.
    /// </summary>
    /// <remarks>
    /// 실제 테넌트에서 본 것들:
    ///   3학년_4반  → 3_4              한글이 빠져 뜻이 반쯤 날아감
    ///   3학년_과학 → 3_               '과학' 이 통째로 사라짐
    ///   늘푸른 학생회 → msteams_83a1ec  Teams 가 자동 생성
    ///   제주도 여행 → 949              숫자만 남음
    /// 한글 이름으로 그룹을 만들면 이렇게 된다. 그래서 Teavel 이 만들 때는
    /// mailNickname 을 영문으로 반드시 받고, 대조할 때는 <b>이름</b>을 기준으로 삼는다.
    /// </remarks>
    public static AliasQuality JudgeAlias(ExistingGroup g)
    {
        var a = g.MailNickname.Trim();
        if (a.Length == 0) return AliasQuality.Degenerate;
        if (AutoAlias.IsMatch(a)) return AliasQuality.AutoGenerated;

        // 글자가 거의 안 남았거나 숫자·구분자뿐이면 뜻이 날아간 것이다.
        var letters = a.Count(char.IsLetter);
        if (letters == 0) return AliasQuality.Degenerate;
        if (a.Length <= 3 && letters <= 1) return AliasQuality.Degenerate;

        return AliasQuality.Fine;
    }

    /// <summary>무더기별 개수를 한 줄로.</summary>
    public static string Summarize(IReadOnlyList<TriagedGroup> triaged)
    {
        var inUse = triaged.Count(t => t.Bucket == TriageBucket.InUse);
        var cand = triaged.Count(t => t.Bucket == TriageBucket.Candidate);
        var sys = triaged.Count(t => t.Bucket == TriageBucket.System);
        var teams = triaged.Count(t => t.Group.IsTeam);

        var s = $"그룹 {triaged.Count}개 (팀 {teams}개) · 쓰이는 것 {inUse}개 · 정리 후보 {cand}개";
        if (sys > 0) s += $" · 건드리면 안 되는 것 {sys}개";
        return s;
    }
}
